
export const PRODUCT_DISPLAY = 'PRODUCT_DISPLAY';
export const GET_ERRORS = 'GET_ERRORS';
export const CATEGORY_DISPLAY = 'CATEGORY_DISPLAY';
export const SUBCATEGORY_DISPLAY = 'SUBCATEGORY_DISPLAY';
export const CART_DISPLAY = 'CART_DISPLAY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const ORDER_DISPLAY = 'ORDER_DISPLAY';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'; 
export const USER_LOADING = 'USER_LOADING';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';